apiVersion: v1
kind: ServiceAccount
metadata:
  name: list-nodes-sa
  namespace: gateway

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: list-nodes
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: list-nodes-binding
subjects:
- kind: ServiceAccount
  name: list-nodes-sa
  namespace: gateway
roleRef:
  kind: ClusterRole
  name: list-nodes
  apiGroup: rbac.authorization.k8s.io
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeexporter
  namespace: gateway
  labels:
    app: nodeexporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeexporter
  template:
    metadata:
      labels:
        app: nodeexporter
    spec:
      serviceAccountName: list-nodes-sa
      containers:
      - name: nodeexporter
        image: ghcr.io/fujifilmimagingproductsandsolutions/nodeexporter:1.0.0
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: dataplaneapi
        env:
        - name: PYTHONUNBUFFERED
          value: "1"            
      imagePullSecrets:
      - name: containerregistries-creds
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
